[package]
name = "falling_sand"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
dyn-clone = "1.0.16"
log = "0.4.20"
getrandom = { version = "0.2.12", features = ["js"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
rand_xoshiro = "0.6.0"
