[package]
name = "web_render"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.67", features = ["CanvasRenderingContext2d"]}
leptos = { version = "0.5.7", features = ["csr", "nightly"] }
falling_sand = { path = "../falling_sand" }
